[package]
name = "pretend-reqwest"
version = "0.1.0"
authors = ["Lucien XU <sfietkonstantin@free.fr>"]
edition = "2018"

[dependencies]
pretend = { path = "../pretend" }
reqwest = { version = "0.11", features = ["json"] }
thiserror = "1.0"
