[package]
name = "pretend-reqwest"
version = "0.1.0"
authors = ["Lucien XU <sfietkonstantin@free.fr>"]
edition = "2018"

[dependencies]
pretend = { path = "../pretend" }
reqwest = { version = "0.11", features = ["json"] }
hyper = ">=0.14, <0.14.5" # Make socket2 compatible with Rust 1.44