- name: breaking
  description: Requires breaking backwards compatibility
  color: c8571e
- name: bug
  description: Something is borken
  color: b3292b
- name: ci
  description: Continuous integration
  color: b7dee7
- name: dependencies
  description: Dependency update
  color: b7dee7
- name: enhancement
  description: Make a feature better
  color: 64b5f6
- name: feature
  description: A new feature
  color: 81c784
- name: good first issue
  description: Something not too complex
  color: ffd54f

# meta
- name: blocked
  description: ""
  color: e0e0e0
- name: duplicate
  description: ""
  color: e0e0e0
- name: invalid
  description: ""
  color: e0e0e0
- name: wontfix
  description: ""
  color: e0e0e0
