name: Continuous integration
on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: "1.44.0"
          default: true

      - run: cargo test

  test-latest:
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          default: true

      - run: cargo test

  test-default-features-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          default: true

      - run: cd tests/default-features-build && cargo test

  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt, clippy
          default: true

      - name: rustfmt
        run: cargo fmt --all -- --check

      - name: Check Clippy lints
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate code coverage report
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: "0.16.0"
          args: "--exclude-files pretend/tests/*.rs --exclude-files pretend-codegen/*.rs --exclude-files pretend-codegen/method/*.rs --exclude-files tests/default-features-build/src/*.rs --exclude-files tests/default-features-build/tests/*.rs --exclude-files tests/default-features-build/tests/builds/*.rs"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
