name: Publish
on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install cargo workspace
        run: cargo install cargo-workspaces

      - name: Cargo login
        run: cargo login ${{ secrets.CARGO_TOKEN }}

      - name: Publish
        run: cargo workspaces publish --from-git --skip-published
