name: Release drafter
on:
  push:
    branches: [main]

jobs:
  update-draft-release:
    runs-on: ubuntu-latest
    steps:
      - uses: toolmantim/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

